apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - configmap.yaml
  - deployment.yaml

# Uncomment when using Kafka mode and have created secret.yaml from secret.yaml.example
# - secret.yaml

commonLabels:
  app: distributedqueue-api
  managed-by: kustomize

images:
  - name: distributedqueue-api
    newTag: latest
